ideas_on_rails_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', {to: 'ideas#index', as: 'root'})
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only:[:create, :destroy]
    get :liked, on: :collection
  end
  resources :users, only:[:new, :create]
 
  resource :session, only:[:new, :create , :destroy]
end

ideas_on_rails_app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
     user ||= User.new # guest user (not logged in)
     if user.is_admin?
      can :manage, :all 
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :destroy, to: :crud)

    can(:crud, Idea) do |post|
      user == post.user
    end

    can(:crud, Review) do |review|
      user == review.user
    end
   

 
  end
end

ideas_on_rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ideas_on_rails_app/app/models/idea.rb
class Idea < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
end

ideas_on_rails_app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates(
    :idea_id,
    uniqueness: {
      scope: :user_id,
      message: "has already been liked"
    }
  )
end

ideas_on_rails_app/app/models/review.rb
class Review < ApplicationRecord
    
    belongs_to :idea
    belongs_to :user
end

ideas_on_rails_app/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: { case_sensitive: false }
    validates :first_name, presence: true
    validates :last_name, presence: true
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea
    
end

ideas_on_rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user
    # `helper_method` makes the method also available for the views

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice:"Please sign in" unless user_signed_in?
    end
end

ideas_on_rails_app/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :find_idea, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user! 
    before_action :authorize_user!, only: [:update, :destroy]

    def new
        @idea = Idea.new
    end
    def create
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save
          redirect_to ideas_path(@idea)
        else
          render :new
        end
    end
    def index
        @ideas = Idea.all
        
    end
    def show

        @reviews = @idea.reviews
        @review = Review.new
       

    end

    def destroy
        @idea.destroy
        redirect_to ideas_path
    end
    def edit

    end

    def update
        if @idea.update idea_params
            redirect_to idea_path(@idea.id)
        else
            render :edit
        end
    end


    private
    

    def find_idea
        @idea =  Idea.find(params[:id])
    end

    def idea_params
      params.require(:idea).permit(:title, :description)
    end
    def authorize_user!
        redirect_to root_path, alert: "Not Authorized!" unless can?(:crud, @idea)
    end
end

ideas_on_rails_app/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        idea = Idea.find params[:idea_id]
        like = Like.new(idea: idea, user: current_user)
        
            if like.save
                flash[:notice] = "Question Liked"
            else
                flash[:alert] = like.errors.full_messages.join(', ')
               
            end
        
            redirect_to ideas_path
        
    end
    
    def destroy
        like = Like.find (params[:id])
        
            if like.destroy
                flash[:notice] = "Idea Unliked"
            else
                flash[:alert] = like.errors.full_messages.join(', ')
                
            end
        
          
            redirect_to ideas_path
    end
    
end

ideas_on_rails_app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def create
        @idea = Idea.find params[:idea_id]
        @review = Review.new(params.require(:review).permit(:body))
        @review.idea = @idea
        @review.user = current_user
        if @review.save
           
            redirect_to idea_path(@idea.id)
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render '/ideas/show'
        end

    end
    def destroy
        @idea = Idea.find params[:idea_id]
        @review = Review.find params[:id]
        if can?(:crud, @review)
            if @review.destroy
                flash[:success] = "Deleted"
                redirect_to idea_path(@idea)
            else
                redirect_to root_path, alert: "can't delete"
            end
        else
            
            redirect_to root_path, alert: "Not Authorized!"
        end

    end
end

ideas_on_rails_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to root_path, notice: "logged in"
        else
            flash[:alert] = "wrong email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "loged out"
    end
end

ideas_on_rails_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'Logged in'
        else
            render :new
        end
    end


    private

    def user_params
        params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation
        )
    end

end

ideas_on_rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ideas_on_rails_app/app/views/ideas/edit.html.erb
<div class="row">
<div class="col-1"></div>
<div class="my-3 py-3 col-11">
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model:@idea do |form|%>

    <%= form.label :title%>
    <br>
    <%= form.text_field :title%>
    <br>
    <%= form.label :description%>
    <br>
    <%= form.text_area :description%>
    <br>
    <%= form.submit nil, class:"btn btn-outline-primary" %>
<% end %>
</div>
</div>

ideas_on_rails_app/app/views/ideas/index.html.erb
<div class="container">
<div class="row">

<% @ideas.each do |idea|%>
<div class="card col-xs-11 col-sm-11 col-md-5 col-lg-3 col-xlg-3 m-4">
    <div class="card-body">
    <h2><%= link_to(idea.title, idea_path(idea.id))%></h2>
    <p><%= idea.description%></p>
    </div>

    <% like = idea.likes.find_by(user: current_user) %>
            <% if like.present? %>
            <%= link_to "Liked", like_path(like),class:"btn btn-primary btn-sm ", method: :delete %>
            <% else %>
            <%= link_to "Like", idea_likes_path(idea),class:"btn btn-primary btn-sm ", method: :post %>
            <% end%>
            </small>
            <small>Likes: <%= idea.likes.count %> </small>
</div>

<%end%>

</div>
</div>

ideas_on_rails_app/app/views/ideas/new.html.erb
<div class="row">
<div class="col-1"></div>
<div class="my-3 py-3 col-11" >
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model:@idea do |form|%>

    <%= form.label :title%>
    <br>
   
    <%= form.text_field :title%>
    
    <br>
    <%= form.label :description%>
    <br>
    <%= form.text_area :description%>
    <br>
    <%= form.submit nil, class:"btn btn-outline-primary" %>
<% end %>
</div>
</div>

ideas_on_rails_app/app/views/ideas/show.html.erb
<div class="container">
  <div class="row ">
    <div class="col-xs-1">
    </div>
 <div class="card col-xs-11 m-4">
 
<h1 ><%= @idea.title%> </h1>

<p ><%= @idea.description%></p>
 
<small>Posted <%= time_ago_in_words(@idea.created_at) %> ago</small>
<br>
<small>
    Created by: <%= @idea.user.first_name %>
</small>
</div>
</div>


<button type="button" class="btn btn-outline-primary">
<%= link_to("Edit", edit_idea_path(@idea.id)) %>
</button>

<button type="button" class="btn btn-outline-primary">
    <%= link_to("Delete", idea_path(@idea.id) ,method: :delete, data:{confirm:"Are you sure?"}) %>
</button>
<br>


  <div class="row ">
    <div class="col-xs-1">
    </div>
 <div class="card col-xs-11 m-4">
<ul>
<% if @review.errors.any? %>
    <% @review.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
    <% end %>
<% end %>
</ul>
<%= form_with(model: [@idea, @review]) do |form|%>
<div>
    <%= form.label :Review%>
    <br>
    <%= form.text_area :body%>
</div>
<%= form.submit %>
<% end %>
<ul>

    <% @reviews.each do |review| %>
        <li>
            <%= review.body %>
            <br>
           
            <small>
            
               Reviewed  <%= time_ago_in_words(review.created_at) %> ago
                <br>
                    Created by: <%= review.user.first_name %>
              <%= link_to("Delete", idea_review_path(@idea.id, review) ,class:"btn btn-light ",method: :delete, data:{confirm:"Are you sure?"}) %>
              <hr>
              
            </small>
        </li>
        
    <% end %>
</ul>
</div> 
   </div> 


</div>

ideas_on_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeasOnRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm justify-content-between navbar-light bg-light">
    <ul class="nav ">
      <a href="/ideas" class="nav-link">Idea Factory</a>
    </ul>
    <ul class="nav">
  
      <a href="/ideas/new" class="nav-link">New Idea</a>
    </ul>
     <% if user_signed_in? %>
          Hello .<%= current_user.first_name %>
        
          <%= link_to "Sign out", session_path, method: :delete, data: {confirm: "Are you sure you want to logout?"} %>
        <% else %>
        <%=  link_to  'Sign In', new_session_path  %>
          
        <%=  link_to  'Sign Up', new_user_path  %>
        <% end %>
 
  <% if flash[:notice].present?%>
        <div class="alert alert-success aler-dismissible fade show" role="alert">
          <%= flash[:notice]%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
          </button>
        </div>
    <% elsif flash[:alert].present?%>
      <div class="alert alert-danger aler-dismissible fade show" role="alert">
          <%= flash[:alert]%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
          </button>
        </div>
    <% end %>
    
  </nav>
    <%= yield %>
  </body>
</html>

ideas_on_rails_app/app/views/users/new.html.erb
<h1>Sign Up </h1>

<%= form_with model: @user do |form| %>
    <% if @user.errors.any?%>
        <p><%= @user.errors.full_messages.join(', ')%></p>
    <% end%>
    <div>
        <%= form.label :first_name%>
        <%= form.text_field :first_name%>
    </div>
    <div>
        <%= form.label :last_name%>
        <%= form.text_field :last_name%>
    </div>
    <div>
        <%= form.label :email%>
        <%= form.text_field :email%>
    </div>
    <div>
        <%= form.label :password%>
        <%= form.text_field :password%>
    </div>
    <div>
        <%= form.label :password_confirmation%>
        <%= form.text_field :password_confirmation%>
    </div>
    <%= form.submit "Sign Up"%>
<% end %>